spring.datasource.url=jdbc:sqlserver://admin_cuong.mssql.somee.com:1433;databaseName=admin_cuong;encrypt=true;trustServerCertificate=true
spring.datasource.username=vucuong2215_SQLLogin_1
spring.datasource.password=123321Cc@
server.port=${PORT:8080}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect